[build]
  command = "yarn next:build"
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  command = "yarn next:dev"
  port = 3000

[functions]
  node_bundler = "esbuild"

